version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: cloudtech_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d cloudtech_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  backend:
    image: 186.232.131.183:5000/backend:latest
    environment:
      DATABASE_URL: postgres://admin:admin123@postgres:5432/cloudtech_db
      JWT_SECRET: supersecretkey
      EMAIL_HOST: smtp.example.com
      EMAIL_PORT: 587
      EMAIL_USER: example@gmail.com
      EMAIL_PASS: pass123
      FRONTEND_URL: http://localhost:3000
    ports:
      - "7001:7001"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  postgres_data:

